"""Prioritized offline catalog. Entries are descriptive and never authorize network use."""
from __future__ import annotations
from .catalog_models import CatalogSource
from .priority_scoring import ScoreFactors,development_score

def _c(source_id,name,publisher,publisher_type,position,priority,authority,domains,wave,rank,*,geo=("France",),official=(),engines=("official_knowledge",),ineos="medium",cssct="medium",cse="medium",payroll="low",protection="low",status="not_investigated",caveats=(),dependencies=(),overlap=()):
 return CatalogSource(source_id,name,publisher,publisher_type,position,"France/EU/international",geo,"existing_internal_connector" if status=="architecture_only" else "unknown",authority,priority,int(priority[-1]),tuple(domains),target_engines=engines,relevance_for_ineos_sarralbe=ineos,relevance_for_cssct=cssct,relevance_for_cse=cse,relevance_for_payroll=payroll,relevance_for_protection_sociale=protection,official_domains=official,possible_access_modes=(),connector_status=status,dependency_sources=dependencies,overlap_with_sources=overlap,development_wave=wave,development_rank=rank,selection_reason="Authority, operational relevance and connector readiness assessed separately.",caveats=caveats)

CATALOG=(
 _c("ineos_internal_sources","Accords et documents INEOS validés","INEOS / parties signataires","unknown","unknown","PRIORITY_0","institutional_information",("company_rules","agreements"),"WAVE_0",1,ineos="very_high",cse="very_high",payroll="very_high",caveats=("internal_scope_and_validity_must_be_verified",)),
 _c("alsace_moselle_local_law","Droit local d'Alsace-Moselle","République française","government","legislative_or_regulatory_authority","PRIORITY_0","primary_law",("local_law","employment_law"),"WAVE_0",2,geo=("Moselle","Bas-Rhin","Haut-Rhin"),official=("legifrance.gouv.fr",),ineos="very_high",payroll="high",status="architecture_only",caveats=("applicability_must_be_verified",)),
 _c("alsace_moselle_health_regime","Régime local d'assurance maladie Alsace-Moselle","Régime local d'assurance maladie","social_security_body","social_security_operator","PRIORITY_0","official_social_security_information",("social_security","health_insurance"),"WAVE_2",6,geo=("Alsace-Moselle",),protection="very_high",payroll="high",caveats=("distinct_from_local_employment_law",)),
 _c("legifrance","Légifrance","DILA","government","legislative_or_regulatory_authority","PRIORITY_1","primary_law",("law","collective_agreements"),"WAVE_0",1,official=("legifrance.gouv.fr","api.piste.gouv.fr"),ineos="very_high",cssct="very_high",cse="very_high",payroll="very_high",status="architecture_only"),
 _c("ccn_chimie","Convention collective nationale des industries chimiques","Partenaires sociaux de la branche","joint_body","joint_governance","PRIORITY_1","primary_law",("collective_agreement","chemical_industry"),"WAVE_0",3,ineos="very_high",cse="very_high",payroll="very_high",dependencies=("legifrance",)),
 _c("judilibre","JUDILIBRE","Cour de cassation","court","judicial_authority","PRIORITY_1","official_case_law",("case_law","employment_law"),"WAVE_0",2,official=("courdecassation.fr","api.piste.gouv.fr"),ineos="high",cse="high",payroll="high",status="architecture_only"),
 _c("eur_lex","EUR-Lex","Union européenne","european_institution","legislative_or_regulatory_authority","PRIORITY_1","primary_law",("eu_law",),"WAVE_2",10,geo=("European Union",),official=("eur-lex.europa.eu",),cssct="high"),
 _c("cjeu","Cour de justice de l'Union européenne","CJUE","court","judicial_authority","PRIORITY_1","official_case_law",("eu_case_law",),"WAVE_3",12,geo=("European Union",),official=("curia.europa.eu",)),
 _c("conseil_constitutionnel","Conseil constitutionnel","Conseil constitutionnel","court","judicial_authority","PRIORITY_1","official_case_law",("constitutional_law",),"WAVE_4",20,official=("conseil-constitutionnel.fr",)),
 _c("conseil_etat","Conseil d'État","Conseil d'État","court","judicial_authority","PRIORITY_1","official_case_law",("administrative_case_law",),"WAVE_4",21,official=("conseil-etat.fr",)),
 _c("dreets_grand_est","DREETS Grand Est","Ministère du Travail","government","official_guidance_provider","PRIORITY_2","official_guidance",("employment_law","labour_inspection","social_dialogue"),"WAVE_1",2,geo=("Grand Est",),official=("grand-est.dreets.gouv.fr",),ineos="very_high",cssct="very_high",cse="very_high",payroll="high",caveats=("guidance_is_not_law",)),
 _c("dreets_national","Portail national DREETS","Ministère du Travail","government","official_guidance_provider","PRIORITY_2","official_guidance",("employment","labour_inspection"),"WAVE_2",11,official=("dreets.gouv.fr",),caveats=("guidance_is_not_law",)),
 _c("inspection_travail","Inspection du travail","Ministère du Travail","government","official_guidance_provider","PRIORITY_2","official_guidance",("labour_inspection","employment_law"),"WAVE_2",12,ineos="high",cssct="high",cse="high",caveats=("content_authority_depends_on_exact_document",)),
 _c("ministere_travail","Ministère du Travail","Ministère du Travail","government","official_guidance_provider","PRIORITY_2","official_guidance",("employment_law","policy"),"WAVE_2",13,official=("travail-emploi.gouv.fr",)),
 _c("bulletin_officiel_travail","Bulletin officiel du Travail","Ministère du Travail","government","legislative_or_regulatory_authority","PRIORITY_2","official_regulation",("official_bulletin","employment_law"),"WAVE_3",13,dependencies=("ministere_travail",)),
 _c("cnil","CNIL","CNIL","public_authority","neutral_public_authority","PRIORITY_2","official_guidance",("personal_data","digital"),"WAVE_0",4,official=("cnil.fr",),ineos="high",cssct="high",cse="high",status="architecture_only",caveats=("license_and_access_review_pending",)),
 _c("dreal_grand_est","DREAL Grand Est","Ministère de la Transition écologique","government","official_guidance_provider","PRIORITY_2","official_guidance",("icpe","seveso","environment","inspections"),"WAVE_1",1,geo=("Grand Est",),official=("grand-est.developpement-durable.gouv.fr",),ineos="very_high",cssct="very_high",cse="high",caveats=("general_communication_is_not_site_prescription",)),
 _c("dreal_national","Portail national DREAL","Ministère de la Transition écologique","government","official_guidance_provider","PRIORITY_2","official_guidance",("environment","industrial_risk"),"WAVE_3",14),
 _c("inrs","INRS","INRS","public_research_body","prevention_body","PRIORITY_3","official_prevention_guidance",("occupational_health","prevention"),"WAVE_1",3,official=("inrs.fr",),ineos="very_high",cssct="very_high",cse="high"),
 _c("ineris","INERIS","INERIS","public_research_body","technical_reference_body","PRIORITY_3","official_prevention_guidance",("industrial_risk","environment"),"WAVE_1",4,official=("ineris.fr",),ineos="very_high",cssct="very_high"),
 _c("aida","AIDA","INERIS","public_research_body","technical_reference_body","PRIORITY_3","official_guidance",("icpe","environmental_regulation"),"WAVE_1",5,official=("aida.ineris.fr",),ineos="very_high",cssct="very_high",dependencies=("ineris",),caveats=("distinguish_normative_text_from_documentary_tool",)),
 _c("aria","ARIA","BARPI","government","technical_reference_body","PRIORITY_3","institutional_information",("industrial_accidents","experience_feedback"),"WAVE_1",6,official=("aria.developpement-durable.gouv.fr",),ineos="very_high",cssct="very_high",caveats=("similar_accident_is_not_direct_legal_proof",)),
 _c("georisques","Géorisques","Ministère de la Transition écologique","government","technical_reference_body","PRIORITY_3","institutional_information",("risk_data","environment"),"WAVE_3",2,official=("georisques.gouv.fr",),ineos="high",cssct="high"),
 _c("anact","ANACT","ANACT","public_agency","prevention_body","PRIORITY_3","official_prevention_guidance",("working_conditions","work_organization"),"WAVE_2",1,official=("anact.fr",),cssct="very_high",cse="high"),
 _c("assurance_maladie_risques_professionnels","Assurance Maladie - Risques professionnels","Assurance Maladie","social_security_body","prevention_body","PRIORITY_3","official_prevention_guidance",("occupational_risk","social_security"),"WAVE_2",3,protection="high",cssct="high"),
 _c("anssi","ANSSI","ANSSI","public_authority","technical_reference_body","PRIORITY_3","official_guidance",("cybersecurity",),"WAVE_3",3,official=("cyber.gouv.fr",)),
 _c("echa","ECHA","European Chemicals Agency","european_institution","technical_reference_body","PRIORITY_3","official_regulation",("reach","clp","chemicals"),"WAVE_3",1,geo=("European Union",),official=("echa.europa.eu",),ineos="very_high",cssct="very_high"),
 _c("sante_publique_france","Santé publique France","Santé publique France","public_agency","technical_reference_body","PRIORITY_3","official_guidance",("public_health",),"WAVE_4",14),
 _c("anses","ANSES","ANSES","public_agency","technical_reference_body","PRIORITY_3","official_prevention_guidance",("health_risk","chemicals"),"WAVE_4",13,cssct="high"),
 _c("base_icpe","Base nationale ICPE","Ministère de la Transition écologique","government","technical_reference_body","PRIORITY_3","institutional_information",("icpe","site_data"),"WAVE_2",7,ineos="very_high",cssct="high"),
 _c("icpe_legal_sources","Installations classées et arrêtés préfectoraux","Préfectures / État","government","legislative_or_regulatory_authority","PRIORITY_1","official_regulation",("icpe","site_prescriptions"),"WAVE_1",7,ineos="very_high",cssct="very_high",caveats=("scope_and_current_version_must_be_verified",)),
 _c("oppbtp","OPPBTP","OPPBTP","joint_body","prevention_body","PRIORITY_3","official_prevention_guidance",("prevention_methodology",),"WAVE_4",17,caveats=("complementary_methodological_resource",)),
 _c("code_travail_numerique","Code du travail numérique","Ministère du Travail","government","official_guidance_provider","PRIORITY_4","official_practical_information",("employment_law","practical_information"),"WAVE_0",3,official=("code.travail.gouv.fr",),status="architecture_only",caveats=("not_substitute_for_legal_text",)),
 _c("service_public","Service-Public.fr","DILA","government","official_guidance_provider","PRIORITY_4","official_practical_information",("practical_information",),"WAVE_2",5,official=("service-public.fr",),caveats=("not_primary_law",)),
 _c("ameli","Ameli","Assurance Maladie","social_security_body","social_security_operator","PRIORITY_4","official_social_security_information",("health_insurance","benefits"),"WAVE_2",2,official=("ameli.fr",),protection="very_high",payroll="high"),
 _c("urssaf","URSSAF","URSSAF","social_security_body","social_security_operator","PRIORITY_4","official_social_security_information",("contributions","employment"),"WAVE_2",4,official=("urssaf.fr",),payroll="very_high",protection="high"),
 _c("assurance_retraite","Assurance retraite","Assurance retraite","social_security_body","social_security_operator","PRIORITY_4","official_social_security_information",("retirement",),"WAVE_4",1,protection="high"),
 _c("agirc_arrco","Agirc-Arrco","Agirc-Arrco","joint_body","joint_governance","PRIORITY_4","institutional_information",("supplementary_retirement",),"WAVE_4",2,protection="high",payroll="high"),
 _c("caf","CAF","CNAF","social_security_body","social_security_operator","PRIORITY_4","official_social_security_information",("family_benefits",),"WAVE_4",4,protection="medium"),
 _c("france_competences","France Compétences","France Compétences","public_agency","technical_reference_body","PRIORITY_4","institutional_information",("training","certification"),"WAVE_4",3),
 _c("france_travail","France Travail","France Travail","public_agency","official_guidance_provider","PRIORITY_4","official_practical_information",("employment","job_market"),"WAVE_4",8),
 _c("rncp","Répertoire national des certifications professionnelles","France Compétences","public_agency","technical_reference_body","PRIORITY_4","institutional_information",("certifications","skills"),"WAVE_4",7,dependencies=("france_competences",)),
 _c("france_chimie","France Chimie","France Chimie","employer_federation","employer_side_institution","PRIORITY_5","institutional_information",("chemical_industry","branch_employment","skills"),"WAVE_3",4,official=("francechimie.fr",),ineos="high",cse="medium",caveats=("not_law","not_neutral","identify_employer_positions","never_override_law_collective_agreement_company_agreement_or_case_law","separate_factual_branch_data_from_employer_advocacy")),
 _c("observatoire_chimie","Observatoire des métiers des industries chimiques","Observatoire de branche","professional_observatory","joint_governance","PRIORITY_5","institutional_information",("chemical_jobs","skills"),"WAVE_3",5,ineos="high"),
 _c("opco_2i","OPCO 2i","OPCO 2i","training_body","joint_governance","PRIORITY_5","institutional_information",("training","industry_skills"),"WAVE_3",6,ineos="high"),
 _c("gestis","GESTIS","IFA/DGUV","foreign_public_institution","technical_reference_body","PRIORITY_6","institutional_information",("chemical_substances","occupational_safety"),"WAVE_4",5,geo=("Germany","international"),official=("gestis.dguv.de",),ineos="high",cssct="high",dependencies=("echa","inrs"),caveats=("complementary_foreign_source","never_priority_over_applicable_french_or_eu_rule")),
 _c("edpb","CEPD / EDPB","European Data Protection Board","european_institution","neutral_public_authority","PRIORITY_2","official_guidance",("personal_data","eu_law"),"WAVE_3",9,geo=("European Union",),official=("edpb.europa.eu",)),
 _c("eu_ai_act","Commission européenne - IA Act","Commission européenne","european_institution","official_guidance_provider","PRIORITY_2","official_guidance",("artificial_intelligence","eu_law"),"WAVE_4",10,geo=("European Union",),caveats=("authoritative_text_must_come_from_eur_lex",),dependencies=("eur_lex",)),
 _c("cybermalveillance","Cybermalveillance.gouv.fr","GIP ACYMA","public_agency","official_guidance_provider","PRIORITY_4","official_practical_information",("cybersecurity","practical_information"),"WAVE_4",11),
 _c("data_gouv_fr","data.gouv.fr","DINUM","government","technical_reference_body","PRIORITY_4","institutional_information",("open_data",),"WAVE_4",12,official=("data.gouv.fr",),caveats=("dataset_authority_follows_its_publisher",)),
 _c("ministere_transition_ecologique","Ministère de la Transition écologique","Ministère de la Transition écologique","government","official_guidance_provider","PRIORITY_2","official_guidance",("environment","industrial_risk","policy"),"WAVE_3",15,caveats=("exact_content_authority_must_be_qualified",)),
 _c("assurance_maladie","Assurance Maladie","CNAM","social_security_body","social_security_operator","PRIORITY_4","official_social_security_information",("health_insurance","social_security"),"WAVE_2",8,protection="very_high",overlap=("ameli","assurance_maladie_risques_professionnels")),
 _c("api_entreprise","API Entreprise","DINUM","government","technical_reference_body","PRIORITY_4","institutional_information",("public_data_catalog",),"WAVE_4",18,caveats=("utility_and_access_authorization_must_be_demonstrated",)),
)

CATALOG_BY_ID={source.source_id:source for source in CATALOG}

def get_catalog_source(source_id:str)->CatalogSource: return CATALOG_BY_ID[source_id]
def list_catalog_sources()->tuple[CatalogSource,...]: return CATALOG

SCORE_FACTORS={
 "legifrance":ScoreFactors(25,15,15,8,5,5,4,4),"dreal_grand_est":ScoreFactors(12,8,15,20,10,5,3,3),
 "inrs":ScoreFactors(8,12,15,20,7,5,4,4),"dreets_grand_est":ScoreFactors(15,12,15,10,10,5,3,3),
 "ineris":ScoreFactors(7,6,14,20,7,5,3,3),"aida":ScoreFactors(15,5,13,20,7,5,3,3),
 "aria":ScoreFactors(3,4,14,20,7,5,4,4),"france_chimie":ScoreFactors(1,5,8,10,5,3,3,2),
 "echa":ScoreFactors(18,5,13,20,2,5,3,4),"gestis":ScoreFactors(1,3,8,14,1,4,3,3),
}
DEVELOPMENT_SCORES={source_id:development_score(factors) for source_id,factors in SCORE_FACTORS.items()}
