from enum import StrEnum

class Capability(StrEnum):
 API="API"; RSS="RSS"; ATOM="ATOM"; HTML="HTML"; SITEMAP="SITEMAP"; PDF="PDF"
 OPEN_DATA="OPEN_DATA"; FILE="FILE"; MANUAL="MANUAL"; AUTHENTICATION="AUTHENTICATION"
 CACHE="CACHE"; SYNC="SYNC"; DISCOVERY="DISCOVERY"; SEARCH="SEARCH"; DOWNLOAD="DOWNLOAD"; VERSIONING="VERSIONING"
