"""Public API of the Syndical Reasoning Engine R0."""

from .engine import SyndicalReasoningEngine
from .models import (
    ActionOption,
    ActionPlanStep,
    AvailablePiece,
    CaseFact,
    Citation,
    ConfidentialityLevel,
    ConfidenceLevel,
    FactStatus,
    SourceAssessment,
    SourceContradiction,
    SourceReference,
    SourceVerification,
    SyndicalCaseInput,
    SyndicalReasoningReport,
    UrgencyLevel,
)
from .protocol import PROTOCOL_STEPS, ReasoningStep
from .reference_scenario import REFERENCE_QUESTION, build_reference_case
from .contract_change_engine import (
    ContractChangeReasoningEngine,
    needs_contract_change_reasoning,
)
from .contract_change_models import (
    ChangeDimension,
    ContractChangeAnalysis,
    ContractChangeStrategy,
    EvidencePriority,
    EvidenceRequirement,
    PositionAnalysis,
    PrioritizedQuestion,
    QualificationCandidate,
)
from .contract_change_scenarios import contract_change_scenarios
from .disciplinary_engine import (
    DisciplinaryReasoningEngine,
    needs_disciplinary_reasoning,
)
from .disciplinary_models import (
    DisciplinaryAnalysis,
    DisciplinaryQualification,
    DisciplinaryQualificationCandidate,
    ProtectedEmployeeAnalysis,
)
from .disciplinary_scenarios import disciplinary_scenarios
from .discrimination_articulation import articulate_discrimination_domains
from .discrimination_engine import (
    DiscriminationHarassmentReasoningEngine,
    needs_discrimination_harassment_reasoning,
)
from .discrimination_models import (
    AdverseMeasure,
    ComparatorAssessment,
    ContradictoryPosition,
    DiscriminationHarassmentAnalysis,
    DomainArticulation as DiscriminationDomainArticulation,
    EvidenceCategory as DiscriminationEvidenceCategory,
    EvidenceRequirement as DiscriminationEvidenceRequirement,
    ProtectionStrategy,
    ProtectedCriterion,
    QualificationHypothesis,
    QuestionPriority as DiscriminationQuestionPriority,
    SituationType,
    StatementNature,
    TemporalPrecision,
    TimelineEvent,
    TimelineEventKind,
)
from .discrimination_scenarios import discrimination_harassment_scenarios
from .working_time_articulation import articulate_syndical_domains
from .working_time_engine import (
    WorkingTimeReasoningEngine,
    needs_working_time_reasoning,
)
from .working_time_models import (
    DocumentComparison,
    DomainArticulation,
    EvidenceCategory,
    OnCallObservation,
    PayImpactLikelihood,
    PotentialPayImpact,
    QuestionPriority,
    ScheduleKind,
    ScheduleObservation,
    WorkingOrganization,
    WorkingTimeAnalysis,
    WorkingTimeEvidence,
    WorkingTimeQualification,
    WorkingTimeQuestion,
    WorkingTimeSituation,
    WorkingTimeStrategy,
)
from .working_time_scenarios import working_time_scenarios

__all__ = (
    "ActionOption",
    "ActionPlanStep",
    "AvailablePiece",
    "CaseFact",
    "Citation",
    "ChangeDimension",
    "ConfidentialityLevel",
    "ConfidenceLevel",
    "ContractChangeAnalysis",
    "ContractChangeReasoningEngine",
    "ContractChangeStrategy",
    "DisciplinaryAnalysis",
    "DisciplinaryQualification",
    "DisciplinaryQualificationCandidate",
    "DisciplinaryReasoningEngine",
    "DiscriminationDomainArticulation",
    "DiscriminationEvidenceCategory",
    "DiscriminationEvidenceRequirement",
    "DiscriminationHarassmentAnalysis",
    "DiscriminationHarassmentReasoningEngine",
    "DiscriminationQuestionPriority",
    "DocumentComparison",
    "DomainArticulation",
    "EvidenceCategory",
    "EvidencePriority",
    "EvidenceRequirement",
    "FactStatus",
    "OnCallObservation",
    "PayImpactLikelihood",
    "PotentialPayImpact",
    "PROTOCOL_STEPS",
    "PositionAnalysis",
    "ProtectionStrategy",
    "ProtectedCriterion",
    "ProtectedEmployeeAnalysis",
    "PrioritizedQuestion",
    "REFERENCE_QUESTION",
    "ReasoningStep",
    "QualificationCandidate",
    "QualificationHypothesis",
    "QuestionPriority",
    "SourceAssessment",
    "SourceContradiction",
    "SourceReference",
    "SourceVerification",
    "SituationType",
    "StatementNature",
    "ScheduleKind",
    "ScheduleObservation",
    "SyndicalCaseInput",
    "SyndicalReasoningEngine",
    "SyndicalReasoningReport",
    "TemporalPrecision",
    "TimelineEvent",
    "TimelineEventKind",
    "UrgencyLevel",
    "WorkingOrganization",
    "WorkingTimeAnalysis",
    "WorkingTimeEvidence",
    "WorkingTimeQualification",
    "WorkingTimeQuestion",
    "WorkingTimeReasoningEngine",
    "WorkingTimeSituation",
    "WorkingTimeStrategy",
    "articulate_syndical_domains",
    "articulate_discrimination_domains",
    "build_reference_case",
    "contract_change_scenarios",
    "disciplinary_scenarios",
    "discrimination_harassment_scenarios",
    "needs_contract_change_reasoning",
    "needs_disciplinary_reasoning",
    "needs_discrimination_harassment_reasoning",
    "needs_working_time_reasoning",
    "working_time_scenarios",
    "AdverseMeasure",
    "ComparatorAssessment",
    "ContradictoryPosition",
)
