"""Public API of the Syndical Reasoning Engine R0."""

from .engine import SyndicalReasoningEngine
from .models import (
    ActionOption,
    ActionPlanStep,
    AvailablePiece,
    CaseFact,
    Citation,
    ConfidentialityLevel,
    ConfidenceLevel,
    FactStatus,
    SourceAssessment,
    SourceContradiction,
    SourceReference,
    SourceVerification,
    SyndicalCaseInput,
    SyndicalReasoningReport,
    UrgencyLevel,
)
from .protocol import PROTOCOL_STEPS, ReasoningStep
from .reference_scenario import REFERENCE_QUESTION, build_reference_case
from .contract_change_engine import (
    ContractChangeReasoningEngine,
    needs_contract_change_reasoning,
)
from .contract_change_models import (
    ChangeDimension,
    ContractChangeAnalysis,
    ContractChangeStrategy,
    EvidencePriority,
    EvidenceRequirement,
    PositionAnalysis,
    PrioritizedQuestion,
    QualificationCandidate,
)
from .contract_change_scenarios import contract_change_scenarios
from .cse_consultation_engine import (
    CSEConsultationReasoningEngine,
    NullCSEMemoryLookup,
    needs_cse_consultation_reasoning,
)
from .cse_consultation_models import (
    CSEConsultationAnalysis,
    CSEMemoryLookup,
    CSEMemoryMetadata,
    CSEProjectFacts,
    CSEQualification,
    CSEQuestion,
    CSEStrategy,
    CollectiveDimension,
    ConsultationAssessment,
    DocumentPriority as CSEDocumentPriority,
    DocumentRequest,
    DomainArticulation as CSEDomainArticulation,
    EventNature as CSEEventNature,
    MechanismAnalysis,
    ObstructionAssessment,
    ObstructionRisk,
    ParticipationMechanism,
    ProjectTimelineEvent,
    ProjectType,
    QuestionPriority as CSEQuestionPriority,
)
from .cse_consultation_scenarios import cse_consultation_scenarios
from .disciplinary_engine import (
    DisciplinaryReasoningEngine,
    needs_disciplinary_reasoning,
)
from .disciplinary_models import (
    DisciplinaryAnalysis,
    DisciplinaryQualification,
    DisciplinaryQualificationCandidate,
    ProtectedEmployeeAnalysis,
)
from .disciplinary_scenarios import disciplinary_scenarios
from .discrimination_articulation import articulate_discrimination_domains
from .discrimination_engine import (
    DiscriminationHarassmentReasoningEngine,
    needs_discrimination_harassment_reasoning,
)
from .discrimination_models import (
    AdverseMeasure,
    ComparatorAssessment,
    ContradictoryPosition,
    DiscriminationHarassmentAnalysis,
    DomainArticulation as DiscriminationDomainArticulation,
    EvidenceCategory as DiscriminationEvidenceCategory,
    EvidenceRequirement as DiscriminationEvidenceRequirement,
    ProtectionStrategy,
    ProtectedCriterion,
    QualificationHypothesis,
    QuestionPriority as DiscriminationQuestionPriority,
    SituationType,
    StatementNature,
    TemporalPrecision,
    TimelineEvent,
    TimelineEventKind,
)
from .discrimination_scenarios import discrimination_harassment_scenarios
from .health_absence_articulation import articulate_health_domains
from .health_absence_engine import (
    HealthAbsenceReasoningEngine,
    needs_health_absence_reasoning,
)
from .health_absence_models import (
    ActorResponsibility,
    CompetentActor,
    EvidenceCategory as HealthEvidenceCategory,
    HealthAbsenceAnalysis,
    HealthDocumentComparison,
    HealthDomainArticulation,
    HealthEventKind,
    HealthHypothesis,
    HealthPosition,
    HealthQualification,
    HealthQuestion,
    HealthSituation,
    HealthStrategy,
    HealthTimelineEvent,
    QuestionPriority as HealthQuestionPriority,
    UrgencyCategory,
)
from .health_absence_scenarios import health_absence_scenarios
from .working_time_articulation import articulate_syndical_domains
from .working_time_engine import (
    WorkingTimeReasoningEngine,
    needs_working_time_reasoning,
)
from .working_time_models import (
    DocumentComparison,
    DomainArticulation,
    EvidenceCategory,
    OnCallObservation,
    PayImpactLikelihood,
    PotentialPayImpact,
    QuestionPriority,
    ScheduleKind,
    ScheduleObservation,
    WorkingOrganization,
    WorkingTimeAnalysis,
    WorkingTimeEvidence,
    WorkingTimeQualification,
    WorkingTimeQuestion,
    WorkingTimeSituation,
    WorkingTimeStrategy,
)
from .working_time_scenarios import working_time_scenarios

__all__ = (
    "ActionOption",
    "ActionPlanStep",
    "AvailablePiece",
    "CaseFact",
    "Citation",
    "ChangeDimension",
    "ConfidentialityLevel",
    "ConfidenceLevel",
    "ContractChangeAnalysis",
    "ContractChangeReasoningEngine",
    "ContractChangeStrategy",
    "CSEConsultationAnalysis",
    "CSEConsultationReasoningEngine",
    "CSEDocumentPriority",
    "CSEDomainArticulation",
    "CSEEventNature",
    "CSEMemoryLookup",
    "CSEMemoryMetadata",
    "CSEProjectFacts",
    "CSEQualification",
    "CSEQuestion",
    "CSEQuestionPriority",
    "CSEStrategy",
    "CollectiveDimension",
    "ConsultationAssessment",
    "DisciplinaryAnalysis",
    "DisciplinaryQualification",
    "DisciplinaryQualificationCandidate",
    "DisciplinaryReasoningEngine",
    "DocumentRequest",
    "DiscriminationDomainArticulation",
    "DiscriminationEvidenceCategory",
    "DiscriminationEvidenceRequirement",
    "DiscriminationHarassmentAnalysis",
    "DiscriminationHarassmentReasoningEngine",
    "DiscriminationQuestionPriority",
    "DocumentComparison",
    "DomainArticulation",
    "EvidenceCategory",
    "EvidencePriority",
    "EvidenceRequirement",
    "FactStatus",
    "HealthAbsenceAnalysis",
    "HealthAbsenceReasoningEngine",
    "HealthDocumentComparison",
    "HealthDomainArticulation",
    "HealthEventKind",
    "HealthEvidenceCategory",
    "HealthHypothesis",
    "HealthPosition",
    "HealthQualification",
    "HealthQuestion",
    "HealthQuestionPriority",
    "HealthSituation",
    "HealthStrategy",
    "HealthTimelineEvent",
    "MechanismAnalysis",
    "NullCSEMemoryLookup",
    "ObstructionAssessment",
    "ObstructionRisk",
    "OnCallObservation",
    "PayImpactLikelihood",
    "PotentialPayImpact",
    "ParticipationMechanism",
    "PROTOCOL_STEPS",
    "PositionAnalysis",
    "ProtectionStrategy",
    "ProtectedCriterion",
    "ProtectedEmployeeAnalysis",
    "PrioritizedQuestion",
    "REFERENCE_QUESTION",
    "ReasoningStep",
    "QualificationCandidate",
    "QualificationHypothesis",
    "ProjectTimelineEvent",
    "ProjectType",
    "QuestionPriority",
    "SourceAssessment",
    "SourceContradiction",
    "SourceReference",
    "SourceVerification",
    "SituationType",
    "StatementNature",
    "ScheduleKind",
    "ScheduleObservation",
    "SyndicalCaseInput",
    "SyndicalReasoningEngine",
    "SyndicalReasoningReport",
    "TemporalPrecision",
    "TimelineEvent",
    "TimelineEventKind",
    "UrgencyLevel",
    "UrgencyCategory",
    "WorkingOrganization",
    "WorkingTimeAnalysis",
    "WorkingTimeEvidence",
    "WorkingTimeQualification",
    "WorkingTimeQuestion",
    "WorkingTimeReasoningEngine",
    "WorkingTimeSituation",
    "WorkingTimeStrategy",
    "articulate_syndical_domains",
    "articulate_discrimination_domains",
    "articulate_health_domains",
    "build_reference_case",
    "contract_change_scenarios",
    "cse_consultation_scenarios",
    "disciplinary_scenarios",
    "discrimination_harassment_scenarios",
    "health_absence_scenarios",
    "needs_contract_change_reasoning",
    "needs_cse_consultation_reasoning",
    "needs_disciplinary_reasoning",
    "needs_discrimination_harassment_reasoning",
    "needs_health_absence_reasoning",
    "needs_working_time_reasoning",
    "working_time_scenarios",
    "AdverseMeasure",
    "ComparatorAssessment",
    "ContradictoryPosition",
    "ActorResponsibility",
    "CompetentActor",
)
